### PR TITLE
Add 'Framework :: Trio' classifier to setup.py

### PR DESCRIPTION
**Pull request by njsmith**

### CODE REVIEW

**Comment by Zaab1t** [comment]
While we're at it:
```
Framework :: Curio
Intended Audience :: Developers
License :: OSI Approved :: MIT License
Programming Language :: Python :: 3 :: Only
Topic :: Internet :: WWW/HTTP
```
\* Curio not official classifier

**Comment by njsmith** [comment]
I believe (but have not checked) that PyPI will reject uploads that use unofficial classifiers.

**Comment by SunDwarf** [comment]
It does.

**Comment by njsmith** [comment]
Added the others.

**Pull request merged**
