### PR TITLE
Add raise_for_status method on Response objects

### LINKED ISSUE #82: convenience method `Response.raise_for_status()`
requests `Response` objects have an `raise_for_status()` method that I enjoy using.

http://docs.python-requests.org/en/master/api/#requests.Response.raise_for_status

Please implement this in asks.

### PR DESCRIPTION
**Pull request by carlwgeorge**
Resolves #82

### CODE REVIEW

**Comment by theelous3** [comment]
Hey nice. One thing, the `BadHttpResponse` is specifically for when the server breaks protocol in a way we do not handle, so we can't use it here. Eg, a 400 indicates the response was valid in terms of http but we supplied bad data. We need a new exception.

**Comment by carlwgeorge** [comment]
How about `HTTPError`?  [That's what requests uses](https://github.com/requests/requests/blob/v2.19.1/requests/exceptions.py#L28-L29).  I can add that exception (and use it) in this same pull request if you like.

**Comment by theelous3** [comment]
I'm just debating with myself here about weather we want to mirror requests for this or if we want to do something that makes a little more sense. As I pointed out before I've never been a big fan of the method, so maybe as a user you can give some insight.

My problem is that  `HttpError` is insanely generic and doesn't really add any information. It's similar to saying "there is a problem with the http" rather than what's actually happening, which is just that we are unhappy with the response.

If I think to the stdlib for something similar, I think of `StopIteration`. Not exactly an error, but rather a clever use of exceptions to indicate to other parts of the state of something that's just completed.

I think a similar approach would be good here. `UnwantedResponseException` or something. A critical part of this naming is using Exception over Error, as we're just using exceptions rather than dealing with something broken.

What do you think?

**Comment by theelous3** [comment]
Ok, we found a name. `BadStatus`.

Create a `BadStatus` exception that inherits from asks' base exception, and use that.

**Comment by carlwgeorge** [comment]
My instinct is to reference the names in the HTTP protocol.

- [Client Error](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4)
- [Server Error](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.5)

Based on those, how about `HttpClientError` and `HttpServerError`?  Still uses the error name but at least addresses your concern of `HttpError` being too generic.  For the implementation it might be best to have an `HttpError` that subclasses `AsksException`, and then `HttpClientError` and `HttpServerError` that subclass `HttpError`.

- `AsksException`
  - `HttpError`
    - `HttpClientError`
    - `HttpServerError`

**Comment by theelous3** [comment]
Nah because these aren't issues on the protocol level, so we don't want to imply there is a problem with the protocol. See my last comment as I think we may have posted on top of one another.

**Comment by carlwgeorge** [comment]
Thanks for the feedback. I redid my commit with a new `BadStatus` exception, please review when you're able.

**Comment by carlwgeorge** [comment]
Do you need me to make any other changes in order to merge?

**Comment by theelous3** [comment]
Hey sorry, busy times at the moment. I'll review tomorrow!

**Comment by theelous3** [comment]
Whew. Ok! Seems good :)

Thank you very much for the contrib.

If you happened to feel a strong desire to update the docs I would very much appreciate it. I'm away at the moment and have very limited time with working internet. This way I can just do a quick version bump and pypi push tomorrow when I get a sec.

**Pull request merged**
