### PR TITLE
Use multio instead of the built-in asynclib handler.

### PR DESCRIPTION
**Pull request by SunDwarf**
This prevents some code duplication between libs that want to support
both trio and curio, with the compat code now shared between all of the
libraries.

### CODE REVIEW

**Comment by Zaab1t** [comment]
Maybe alias `multio.init` so the user does not need another import. I like that api better. This way `asks` is not committed to multio, so we can swap it out later if something better comes by :)

**Comment by SunDwarf** [comment]
It already is, `asks.init = multio.init` in `__init__.py`.

**Comment by Zaab1t** [comment]
Confused because you (accidentally?) updated the README too

**Comment by SunDwarf** [comment]
I felt like it was better to have the README use `multio` in case of another lib using it for clarity.

**Pull request merged**
